import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import PrelineScript from "../lib/PrelineScript"
import { ThemeProvider } from "next-themes";
import Provider from "../components/layout/providers";
/* import TransitionEffect from '../components/layout/TransitionEffect' */

const inter = Nunito({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-Nunito',
})

/* export const metadata: Metadata = {
title: 'Create Next App',
description: 'Generated by create next app',
}
 */
export default function RootLayout({ children,}: {children: React.ReactNode}) {
return (
<html lang="en" className={`${inter.variable}`}>

{/* <head>
  <title>My page title</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="icon" href="/favicon.ico" />
</head> */}
{/* <TransitionEffect /> */}

<body className="min-h-screen mx-auto bg-white dark:bg-gray-900">
    <Provider>
     <PrelineScript />
      <main className=''>
      <Navbar />
      {children}
      <Footer />
    </main>
  </Provider>
</body>

</html>
)
}