import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import PrelineScript from "../lib/PrelineScript"

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,}: {children: React.ReactNode}) {
  return (
    <html lang="en"> 
    	<head>
		<title>My page title</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
	</head>
   

      <body className={inter.className}>
        <PrelineScript />
        <main className={`${inter.variable} font-sans bg-light`}>
   
        <Navbar />

        {children}

        <Footer />

   
          </main>


        </body>
    </html>
  )
}
